--  SCORE PACKAGE

CREATE OR REPLACE PACKAGE SCOREPACKAGE AS
-- GETALL SCORES
PROCEDURE GETALL;

-- UPDATE SCORE
PROCEDURE UPDATESCORE(
    SCOREID SCORE.ID%TYPE,
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    );
    
-- CREATE SCORE
PROCEDURE CREATESCORE(
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    );
    
-- DELETE SCORE
PROCEDURE DELETESCORE(SCOREID SCORE.ID%TYPE);

END SCOREPACKAGE;