--  CORRECT ANSWER PACKAGE

CREATE OR REPLACE PACKAGE CorrectAnswerPackage AS


    -- Correct Answer CRUD Operations
    PROCEDURE CorrectAnswerCRUD(
        func IN VARCHAR DEFAULT NULL,
        CANSWERID CORRECTANSWER.ID%TYPE DEFAULT NULL,
        QOID CORRECTANSWER.QUESTIONOPTIONID%TYPE DEFAULT NULL );
   
END CorrectAnswerPackage;
