--   CORRECT ANSWER PACKAGE BODY

CREATE OR REPLACE PACKAGE BODY CORRECTANSWERPACKAGE AS
----------------------------------------------------
--  GET ALL

PROCEDURE GETALL AS
C_ALL SYS_REFCURSOR;
BEGIN
OPEN C_ALL FOR
SELECT * FROM CORRECTANSWER;
DBMS_SQL.RETURN_RESULT(C_ALL);
END GETALL;
----------------------------------------------------
-- UPDATE CORRECT ANSWER

PROCEDURE UPDATECORRECTANSWER(
    CANSWERID CORRECTANSWER.ID%TYPE,
    QOID CORRECTANSWER.QUESTIONOPTIONID%TYPE
    ) AS
BEGIN
UPDATE CORRECTANSWER SET
    QUESTIONOPTIONID  = QOID
    WHERE ID  = CANSWERID;
COMMIT;
END UPDATECORRECTANSWER;
----------------------------------------------------
-- CREATE CORRECT ANSWER

PROCEDURE CREATECORRECTANSWER(
        QOID CORRECTANSWER.QUESTIONOPTIONID%TYPE
    ) AS
BEGIN
    INSERT INTO CORRECTANSWER (QUESTIONOPTIONID)
    VALUES (QOID);
COMMIT;
END CREATECORRECTANSWER;
----------------------------------------------------
-- DELETE CORRECT ANSWER

PROCEDURE DELETECORRECTANSWER(CANSWERID CORRECTANSWER.ID%TYPE) AS
BEGIN
    DELETE FROM CORRECTANSWER 
    WHERE ID = CANSWERID;
COMMIT;
END DELETECORRECTANSWER;
------------------------------------------------------
END CORRECTANSWERPACKAGE;

--******************************************************************************