-- Start Code

-- Create Exam Procedure Test
DECLARE
  CID NUMBER;
  EXTITLE VARCHAR2(50);
  PASSC VARCHAR2(8);
  DES VARCHAR2(300);
  EXLEVEL VARCHAR2(12);
  SUCCMARK FLOAT;
  PRICE FLOAT;
  STDATE TIMESTAMP;
  ENDATE TIMESTAMP;
  ST VARCHAR2(7);
  CREATEDATE TIMESTAMP;
BEGIN
  CID := 1;
  EXTITLE := 'Python 101';
  PASSC := '1234567';
  DES := NULL;
  EXLEVEL := 'Beginner';
  SUCCMARK := 6;
  PRICE := 0;
  STDATE := '22-MAY-22';
  ENDATE := '22-MAY-22';
  ST := 'ENABLE';
  CREATEDATE := '22-MAY-22';

  EXAMPACKAGE.CREATEEXAM(
    CID => CID,
    EXTITLE => EXTITLE,
    PASSC => PASSC,
    DES => DES,
    EXLEVEL => EXLEVEL,
    SUCCMARK => SUCCMARK,
    PRICE => PRICE,
    STDATE => STDATE,
    ENDATE => ENDATE,
    ST => ST,
    CREATEDATE => CREATEDATE
  );
--rollback; 
END;
/

-- Get Exams Procedure Test
BEGIN
  EXAMPACKAGE.GETEXAMS();
--rollback; 
END;
/

-- Update Exam Procedure Test
DECLARE
  EXID NUMBER;
  CID NUMBER;
  EXTITLE VARCHAR2(50);
  PASSC VARCHAR2(8);
  DES VARCHAR2(300);
  EXLEVEL VARCHAR2(12);
  SUCCMARK FLOAT;
  PRICE FLOAT;
  STDATE TIMESTAMP;
  ENDATE TIMESTAMP;
  ST VARCHAR2(7);
  CREATEDATE TIMESTAMP;
BEGIN
  EXID := 4;
  CID := 1;
  EXTITLE := 'Hello world';
  PASSC := '123123';
  DES := NULL;
  EXLEVEL := 'Intermediate';
  SUCCMARK := 50;
  PRICE := 199.23;
  STDATE := '23-MAY-22';
  ENDATE := '25-MAY-22';
  ST := 'DISABLE';
  CREATEDATE := '22-MAY-22';

  EXAMPACKAGE.UPDATEEXAM(
    EXID => EXID,
    CID => CID,
    EXTITLE => EXTITLE,
    PASSC => PASSC,
    DES => DES,
    EXLEVEL => EXLEVEL,
    SUCCMARK => SUCCMARK,
    PRICE => PRICE,
    STDATE => STDATE,
    ENDATE => ENDATE,
    ST => ST,
    CREATEDATE => CREATEDATE
  );
--rollback; 
END;
/

-- Search Exam Procedure Test
DECLARE
  EXTITLE VARCHAR2(50);
  EXLEVEL VARCHAR2(12);
  SUCCMARK FLOAT;
  PRICE FLOAT;
  STDATE TIMESTAMP;
  ENDATE TIMESTAMP;
  CREATEDATE TIMESTAMP;
BEGIN
  EXTITLE := 'ello';
  EXLEVEL := NULL;
  SUCCMARK := NULL;
  PRICE := NULL;
  STDATE := '22-MAY-22';
  ENDATE := '25-MAY-22';
  CREATEDATE := NULL;

  EXAMPACKAGE.SEARCHEXAM(
    EXTITLE => EXTITLE,
    EXLEVEL => EXLEVEL,
    SUCCMARK => SUCCMARK,
    PRICE => PRICE,
    STDATE => STDATE,
    ENDATE => ENDATE,
    CREATEDATE => CREATEDATE
  );
--rollback; 
END;
/

-- Delete Exam Procedure Test
DECLARE
  EXID NUMBER;
BEGIN
  EXID := 4;

  EXAMPACKAGE.DELETEEXAM(
    EXID => EXID
  );
--rollback; 
END;
/

-- End Code