CREATE OR REPLACE PACKAGE PHONENUMBERPACKAGE AS
--GETALL
PROCEDURE GETALL;

--UPDATE
PROCEDURE UPDATEPHONENUMBER(
    PHNUMID PHONENUMBER.ID%TYPE,
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );

--CREATE
PROCEDURE CREATEPHONENUMBER(
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );

--DELETE
PROCEDURE DELETEPHONENUMBER(PHNUMID PHONENUMBER.ID%TYPE);

END PHONENUMBERPACKAGE;