CREATE OR REPLACE PACKAGE PHONENUMBERPACKAGE AS
--GETALL
PROCEDURE GETALL;

--UPDATE
PROCEDURE UPDATEPHONENUMBER(
    PHNUMID PHONENUMBER.ID%TYPE,
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );

--CREATE
PROCEDURE CREATEPHONENUMBER(
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );

--DELETE
PROCEDURE DELETEPHONENUMBER(PHNUMID PHONENUMBER.ID%TYPE);

END PHONENUMBERPACKAGE;


--   PHONE NUMBER PACKAGE BODY 
CREATE OR REPLACE PACKAGE BODY PHONENUMBERPACKAGE AS
----------------------------------------------------
--  GET ALL

PROCEDURE GETALL AS
C_ALL SYS_REFCURSOR;
BEGIN
OPEN C_ALL FOR
SELECT * FROM PHONENUMBER;
DBMS_SQL.RETURN_RESULT(C_ALL);
END GETALL;
----------------------------------------------------
-- UPDATE PHONE NUMBER

PROCEDURE UPDATEPHONENUMBER(
    PHNUMID PHONENUMBER.ID%TYPE,
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    ) AS
BEGIN
UPDATE PHONENUMBER SET
    PHONENUM = PHNUM,
    ACCOUNTID   = ACCID
    WHERE ID    = PHNUMID;
COMMIT;
END UPDATEPHONENUMBER;
----------------------------------------------------
-- CREATE PHONE NUMBER

PROCEDURE CREATEPHONENUMBER(
    PHNUM PHONENUMBER.PHONENUM%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    ) AS
BEGIN
    INSERT INTO PHONENUMBER (PHONENUM,ACCOUNTID)
    VALUES (PHNUM,ACCID);
COMMIT;
END CREATEPHONENUMBER;
----------------------------------------------------

----------------------------------------------------

PROCEDURE DELETEPHONENUMBER(PHNUMID PHONENUMBER.ID%TYPE) AS
BEGIN
    DELETE FROM PHONENUMBER 
    WHERE ID = PHNUMID;
COMMIT;
END DELETEPHONENUMBER;
------------------------------------------------------
END PHONENUMBERPACKAGE;
