--  PHONE NUMBER PACKAGE

CREATE OR REPLACE PACKAGE PHONENUMBERPACKAGE AS
-- GETALL PHONE NUMBERS
PROCEDURE GETALL;

-- UPDATE PHONE NUMBER
PROCEDURE UPDATEPHONENUMBER(
    PHNUMID PHONENUMBER.ID%TYPE,
    PHNUM PHONENUMBER.PHONENUMBER%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );
    
-- CREATE PHONE NUMBER
PROCEDURE CREATEPHONENUMBER(
    PHNUM PHONENUMBER.PHONENUMBER%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    );
    
-- DELETE PHONE NUMBER
PROCEDURE DELETEPHONENUMBER(PHNUMID PHONENUMBER.ID%TYPE);

END PHONENUMBERPACKAGE;


--   PHONE NUMBER PACKAGE BODY

CREATE OR REPLACE PACKAGE BODY PHONENUMBERPACKAGE AS
----------------------------------------------------
--  GET ALL

PROCEDURE GETALL AS
C_ALL SYS_REFCURSOR;
BEGIN
OPEN C_ALL FOR
SELECT * FROM PHONENUMBER;
DBMS_SQL.RETURN_RESULT(C_ALL);
END GETALL;
----------------------------------------------------
-- UPDATE PHONE NUMBER

PROCEDURE UPDATEPHONENUMBER(
    PHNUMID PHONENUMBER.ID%TYPE,
    PHNUM PHONENUMBER.PHONENUMBER%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    ) AS
BEGIN
UPDATE PHONENUMBER SET
    PHONENUMBER = PHNUM,
    ACCOUNTID   = ACCID
    WHERE ID    = PHNUMID;
COMMIT;
END UPDATEPHONENUMBER;
----------------------------------------------------
-- CREATE PHONE NUMBER

PROCEDURE CREATEPHONENUMBER(
    PHNUM PHONENUMBER.PHONENUMBER%TYPE,
    ACCID PHONENUMBER.ACCOUNTID%TYPE
    ) AS
BEGIN
    INSERT INTO PHONENUMBER (PHONENUMBER,ACCOUNTID)
    VALUES (PHNUM,ACCID);
COMMIT;
END CREATEPHONENUMBER;
----------------------------------------------------
-- DELETE PHONE NUMBER


PROCEDURE DELETEPHONENUMBER(PHNUMID PHONENUMBER.ID%TYPE) AS
BEGIN
    DELETE FROM PHONENUMBER 
    WHERE ID = PHNUMID;
COMMIT;
END DELETEPHONENUMBER;
------------------------------------------------------
END PHONENUMBERPACKAGE;