--  SCORE PACKAGE

CREATE OR REPLACE PACKAGE SCOREPACKAGE AS
-- GETALL SCORES
PROCEDURE GETALL;

-- UPDATE SCORE
PROCEDURE UPDATESCORE(
    SCOREID SCORE.ID%TYPE,
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    );
    
-- CREATE SCORE
PROCEDURE CREATESCORE(
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    );
    
-- DELETE SCORE
PROCEDURE DELETESCORE(SCOREID SCORE.ID%TYPE);

END SCOREPACKAGE;


--   SCORE PACKAGE BODY

CREATE OR REPLACE PACKAGE BODY SCOREPACKAGE AS
----------------------------------------------------
--  GET ALL

PROCEDURE GETALL AS
C_ALL SYS_REFCURSOR;
BEGIN
OPEN C_ALL FOR
SELECT * FROM SCORE;
DBMS_SQL.RETURN_RESULT(C_ALL);
END GETALL;
----------------------------------------------------
-- UPDATE SCORE

PROCEDURE UPDATESCORE(
    SCOREID SCORE.ID%TYPE,
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    ) AS
BEGIN
UPDATE SCORE SET
    GRADE     = SCGRADE,
    STATUS    = SCSTATUS,
    EXAMID    = EXID,
    ACCOUNTID = ACCID
    WHERE ID  = SCOREID;
COMMIT;
END UPDATESCORE;
----------------------------------------------------
-- CREATE SCORE

PROCEDURE CREATESCORE(
    SCGRADE SCORE.GRADE%TYPE,
    SCSTATUS SCORE.STATUS%TYPE,
    EXID SCORE.EXAMID%TYPE,
    ACCID SCORE.ACCOUNTID%TYPE
    ) AS
BEGIN
    INSERT INTO SCORE (GRADE,STATUS,EXAMID,ACCOUNTID)
    VALUES (SCGRADE,SCSTATUS,EXID,ACCID);
COMMIT;
END CREATESCORE;
----------------------------------------------------
-- DELETE SCORE

PROCEDURE DELETESCORE(SCOREID SCORE.ID%TYPE) AS
BEGIN
    DELETE FROM SCORE 
    WHERE ID = SCOREID;
COMMIT;
END DELETESCORE;
------------------------------------------------------
END SCOREPACKAGE;

--******************************************************************************

